name          'elibus-oracle_webgate'
version       '0.1.1'
source        'https://github.com/elibus/puppet-oracle_webgate'
author        'Marco Tizzoni'
license       'Apache 2.0'
summary       'Install and configure Oracle Webgate'
description   ''
project_page  'https://github.com/elibus/puppet-oracle_webgate'

dependency 'puppetlabs/stdlib'
